// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ssl-game-controller
SSL game controller


    Schemes:
      http
    Host: localhost:8081
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
