// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "SSL game controller",
    "title": "ssl-game-controller",
    "version": "1.0.0"
  },
  "host": "localhost:8081",
  "basePath": "/api",
  "paths": {
    "/card": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "card"
        ],
        "summary": "Add a new card",
        "operationId": "addCard",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "Card": {
      "type": "object",
      "properties": {
        "forTeam": {
          "type": "string",
          "enum": [
            "yellow",
            "blue"
          ]
        },
        "kind": {
          "type": "string",
          "enum": [
            "yellow",
            "red"
          ]
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "SSL game controller",
    "title": "ssl-game-controller",
    "version": "1.0.0"
  },
  "host": "localhost:8081",
  "basePath": "/api",
  "paths": {
    "/card": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "card"
        ],
        "summary": "Add a new card",
        "operationId": "addCard",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Card"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "Card": {
      "type": "object",
      "properties": {
        "forTeam": {
          "type": "string",
          "enum": [
            "yellow",
            "blue"
          ]
        },
        "kind": {
          "type": "string",
          "enum": [
            "yellow",
            "red"
          ]
        }
      }
    }
  }
}`))
}
