// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddCardOKCode is the HTTP code returned for type AddCardOK
const AddCardOKCode int = 200

/*AddCardOK OK

swagger:response addCardOK
*/
type AddCardOK struct {
}

// NewAddCardOK creates AddCardOK with default headers values
func NewAddCardOK() *AddCardOK {

	return &AddCardOK{}
}

// WriteResponse to the client
func (o *AddCardOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
